require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/meios_culturas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MeioCultura. As you add validations to MeioCultura, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MeioCultura.create! valid_attributes
      get meios_culturas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      meio_cultura = MeioCultura.create! valid_attributes
      get meio_cultura_url(meio_cultura)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_meio_cultura_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      meio_cultura = MeioCultura.create! valid_attributes
      get edit_meio_cultura_url(meio_cultura)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MeioCultura" do
        expect {
          post meios_culturas_url, params: { meio_cultura: valid_attributes }
        }.to change(MeioCultura, :count).by(1)
      end

      it "redirects to the created meio_cultura" do
        post meios_culturas_url, params: { meio_cultura: valid_attributes }
        expect(response).to redirect_to(meio_cultura_url(MeioCultura.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MeioCultura" do
        expect {
          post meios_culturas_url, params: { meio_cultura: invalid_attributes }
        }.to change(MeioCultura, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post meios_culturas_url, params: { meio_cultura: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested meio_cultura" do
        meio_cultura = MeioCultura.create! valid_attributes
        patch meio_cultura_url(meio_cultura), params: { meio_cultura: new_attributes }
        meio_cultura.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the meio_cultura" do
        meio_cultura = MeioCultura.create! valid_attributes
        patch meio_cultura_url(meio_cultura), params: { meio_cultura: new_attributes }
        meio_cultura.reload
        expect(response).to redirect_to(meio_cultura_url(meio_cultura))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        meio_cultura = MeioCultura.create! valid_attributes
        patch meio_cultura_url(meio_cultura), params: { meio_cultura: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested meio_cultura" do
      meio_cultura = MeioCultura.create! valid_attributes
      expect {
        delete meio_cultura_url(meio_cultura)
      }.to change(MeioCultura, :count).by(-1)
    end

    it "redirects to the meios_culturas list" do
      meio_cultura = MeioCultura.create! valid_attributes
      delete meio_cultura_url(meio_cultura)
      expect(response).to redirect_to(meios_culturas_url)
    end
  end
end
